require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'NikeShopApp_RNFirebase' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-google-signin/google-signin'

  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

  target 'NikeShopApp_RNFirebaseTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'NikeShopApp_RNFirebase-tvOS' do
  # Pods for NikeShopApp_RNFirebase-tvOS

  target 'NikeShopApp_RNFirebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
